apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  
spec:
  project: default
  source:
    path: 3.argocd-apps/apps
    repoURL: https://github.com/hojun121/eks-setup.git
    targetRevision: main

  destination:
    namespace: default
    server: https://kubernetes.default.svc
