apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario
  namespace: argocd
spec:
  project: default
  source:
    path: 3.argocd-apps/charts/mario-helm
    repoURL: https://github.com/hojun121/eks-setup.git
    targetRevision: main

  destination:
    namespace: mario
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
