---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pjh-vpc
  region: ap-northeast-2
  version: "1.26"  
vpc: 
  id: vpc-04a7039c699756c59
  subnets:
    public:
      PublicSubnet01:
        az: a
        id: subnet-0c68d9f71ce7ddc72
      PublicSubnet02:
        az: b
        id: subnet-0c943b270afa7e9e2
    private:
      PrivateSubnet01:
        az: a
        id: subnet-0362af0bc82f085be
      PrivateSubnet02:
        az: b
        id: subnet-0216f45e0f6f57cee
secretsEncryption:
  keyARN: arn:aws:kms:ap-northeast-2:273349345035:key/a85f5fa2-252f-4acd-9271-2df96678dece

managedNodeGroups:
  - name: managed-ng-private-01
    instanceType: m5.xlarge
    subnets:
      - subnet-0362af0bc82f085be
      - subnet-0216f45e0f6f57cee
    desiredCapacity: 3
    privateNetworking: true
    minSize: 3
    maxSize: 9
    volumeSize: 200
    volumeType: gp3
    volumeEncrypted: true
    amiFamily: AmazonLinux2
    labels:
      nodegroup-type: "managed-backend-workloads"
    ssh: 
      publicKeyPath: "/root/.ssh/id_rsa.pub"
    iam:
      attachPolicyARNs:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true
        efs: true
        
cloudWatch:
    clusterLogging:
        enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
